
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1441297
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: course_project_development

test:
  <<: *default
  database: course_project_test

